---
# Playbook for the basic setup for a Ploneserver

- hosts: ploneservers
  user: svx
  sudo: yes
  vars_files:
  - group_vars/ploneservers_vars.yml

  roles:
#  - apt-update
#  - apt-upgrade
#  - ploneservers_packages
  - create_user
#  - ploneuser_setup

#  handlers:
#  - name: restart ssh
#    action: service name name=ssh state=restarted
