---
# This role will install unattended-upgrades

- name: Install Nginx
  apt: name={{item}} state=present
  with_items:
    - unattended-upgrades

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

# todo: we need configure a template with da settings, set mail
