---
# This role installs all needed packages for a Ploneserver

- name: Install all packages we need
  apt: name={{item}} state=present
  with_items:
    - htop
    - python-virtualenv
    - build-essential
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libbz2-dev
    - zlib1g-dev
    - python-setuptools
    - python-dev
    - libjpeg62-dev
    - libreadline-gplv2-dev
    - python-imaging
    - wv
    - poppler-utils



