---
# This role installs all needed packages for a Ploneserver

- name: Install all packages we need
  apt: name={{item}} state=present
  with_items:
    - htop
    - python-virtualenv
    - build-essential
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libbz2-dev
    - zlib1g-dev
    - python-setuptools
    - python-dev
    - libjpeg62-dev
    - libreadline-gplv2-dev
    - python-imaging
    - wv
    - poppler-utils
    - python-psutil

- name: Download and Install ZPS
  command: cd /root && /usr/bin/wget -P http://www.apt.leftxs.org/stable/python-rt.zps_0.9.4-1_all.deb && dpkg -i python-rt.zps_0.9.4-1_all.deb

