---
# This role will setup a user

- name: Create User
  user: name={{ user_name }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

- name: create ssh dir for User
  file: state=directory path=/home/{{ user_name }}/.ssh/ mode=700

- name: upload ssh keys for User
  action: authorized_key user={{ user_name }} key='$FILE(/home/svx/.ssh/id_rsa.pub)'

- name: Upload bashrc
  copy: src=../files/bashrc dest=/home/{{ user_name }}/.bashrc owner={{ user_name }} mode=0644

- name: Upload vimrc
  copy: src=../files/vimrc dest=/home/{{ user_name }}/.vimrc owner={{ user_name }} mode=0644

- name: Upload vim dir
  local_action: rsync -avz ../files/vim {{ inventory_hostname }}:/home/{{ user_name }}/.vim

#- name: add user to allowes user in /etc/sshd
#  lineinfile: dest=/etc/ssh/sshd_config backup=yes regexp='^UseLogin' insertafter='#UseLogin' line='AllowUsers {{ user_name }}'

- name: Upload ssh config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart sshd
