---
# This role will setup a user

- name: Create User
  user: name={{ user_name }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

- name: create ssh dir for User
  file: state=directory path=/home/{{ user_name }}/.ssh/ mode=700

- name: upload ssh keys for User
  action: authorized_key user={{ user_name }} key='$FILE(/home/svx/.ssh/id_rsa.pub)'

- name: Upload bash_profile
  copy: src=../files/bash_profile dest=/home/{{ user_name }}/.bash_profile owner={{ user_name }} mode=0644

- name: add user to allowes user in /etc/sshd
  lineinfile: dest=/etc/ssh/sshd_config regexp='^UseLogin' insertafter='#UseLogin' line='AllowUsers {{ user_name }}'
