---
# This role will install, configure a munin-node

name: Install munin-node
apt: name={{item}} state=present
with_items:
  - munin-node
  - munin-plugins-extra

name: Add server ip to allow check
action: lineinfile dest=/etc/munin/munin-node.conf #rest still to come

# todo: add line with munin-server ip
# todo: configure zope/plone plugin
# todo: configure/setup nginx
# todp: configure main munin-plugins conf
